import math

RES = WIDTH,HEIGHT = 1366,768
FPS = 60
HALF_WIDTH = WIDTH //2
HALF_HEIGHT = HEIGHT //2
TILE =64

Player_POS = 12.5, 49
Player_ANGLE = 0
Player_SPEED = 0.004
Player_ROT_SPEED = 0.002
Player_Size_Scale = 5
PLAYER_MAX_HEALTH = 100

MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30,30,30)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS =WIDTH //2
HALF_NUM_RAYS = NUM_RAYS //2
DELTA_ANGLE = FOV /NUM_RAYS
MAX_DEPTH= 30

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2